[character]
success_symbol = "[➜](bold green)"
error_symbol   = "[➜](bold red)"
vicmd_symbol   = "[↫](bold blue)"


[cmd_duration]
format = "\nrun-time: [$duration](bold blue)"


[git_status]
style      = "bold blue"
untracked  = "."
conflicted = "!"
modified   = "[~](bold yellow)"

