# Default colors
[colors.primary]
background = '#000000'
foreground = '#C0C7C8'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#E53935'
green   = '#0DBC79'
yellow  = '#FBC02D'
blue    = '#2472c8'
magenta = '#C71585'
cyan    = '#039BE5'
white   = '#F5F5F5'

# Bright colors
[colors.bright]
black   = '#666666'
red     = '#DC143C'
green   = '#00FF7F'
yellow  = '#FFEB3B'
blue    = '#1E90FF'
magenta = '#FF1493'
cyan    = '#00BFFF'
white   = '#FFFFFF'

[window]
title         = "Terminal"
dynamic_title = false
opacity       = 0.75

[font]
normal      = { family = "Cascadia Mono", style = "Regular" }
bold        = { family = "Cascadia Mono", style = "Bold" }
italic      = { family = "Cascadia Mono", style = "Italic" }
bold_italic = { family = "Cascadia Mono", style = "Bold Italic" }
size        = 11.5

[cursor]
style     = { shape = "Beam", blinking = "On" }
thickness = 0.01

